checks:
    php:
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_unnecessary_concatenation: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        align_assignments: false
        classes_in_camel_caps: true
        encourage_postdec_operator: true
        encourage_single_quotes: true
        fix_line_ending: true
        function_in_camel_caps: true
        line_length:
            max_length: '200'
        more_specific_types_in_doc_comments: true
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            abstract_class_name: ^Abstract|Factory$
            utility_class_name: 'Utils?$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
        newline_at_end_of_file: true
        no_goto: true
        no_long_variable_names:
            maximum: '20'
        no_short_method_names:
            minimum: '3'
        optional_parameters_at_the_end: true
        overriding_parameter: true
        param_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        parameters_in_camelcaps: true
        phpunit_assertions: true
        prefer_while_loop_over_for_loop: true
        properties_in_camelcaps: true
        return_doc_comment_if_not_inferrable: true
        return_doc_comments: true
        simplify_boolean_return: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true

filter: {  }
coding_style:
    php:
        indentation:
            general:
                size: 1
build:
    nodes:
        analysis:
            project_setup:
                override: ['true']
            tests:
                    override:
                        -
                            command: 'vendor/bin/phpunit --coverage-clover=results'
                            coverage:
                                file: 'results'
                                format: 'clover'